### ISSUE TITLE
Add PHP 7 compatibility

### ISSUE THREAD

**Issue by laukstein** [expressif/win-dist#1]
The modules doesn't work on PHP 7, log:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '\php\ext\php_libevent.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\php\ext\php_propro.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\php\ext\php_raphf.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\php\ext\php_http.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; EpollSocketServer has a deprecated constructor in ...server.php on line 6
```

Any alternative on Windows?

**Comment by ichiriac** [comment]
i've many issues to fix in order to build the extension with php7 - 
see https://wiki.php.net/phpng-upgrading 

I've started to fork and fix the libevent bindings but takes time :
https://github.com/expressif/pecl-event-libevent

.... work in progress ...

**Comment by ichiriac** [comment]
... build pass ...

but not tested yet - streams are really impacted by changes on the new php 7 version

I would be lucky if this version passes tests :)

If it fails open an issue here : https://github.com/expressif/pecl-event-libevent (i will rebuild with all versions when it will fixed)

**Comment by laukstein** [comment]
Testing https://github.com/expressif/win-dist/archive/php-7.0-ts-x64.zip
still doesn't work, see:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '\php\ext\php_libevent.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0
```

https://github.com/expressif/pecl-event-libevent doesn't let to open Issues, only to do Pull requests.

**Comment by ichiriac** [comment]
could you paste the output of : 

```
php -v 
php -i | findstr Architecture
php -i | findstr Zend
```

**Comment by laukstein** [comment]
Maybe it is actually recent XAMPP v7.0.0 or PHP 7.0.0 issue, see:

>php -v

```
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_libevent.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_libevent.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0

Warning: Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0
PHP 7.0.0 (cli) (built: Dec  3 2015 11:36:59) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

>php -i | findstr Architecture

```
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_libevent.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0
Architecture => x86
zend_mm_heap corrupted
```

>php -i | findstr Zend

```
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_curl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mbstring.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_mysqli.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_openssl.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '\xampp\php\ext\php_libevent.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  Cannot open '\xampp\php\extras\browscap.ini' for reading in Unknown on line 0
Zend Extension => 320151012
Zend Extension Build => API320151012,TS,VC14
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => disabled
This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
zend_mm_heap corrupted
```

I'll emailed it to XAMPP developer team too.

**Comment by ichiriac** [comment]
not directly the fault of XAMPP - actually you are using a PHP 7.0.0 ZTS (Thread Safe) in x86 mode 

I have compiled my modules in x64 mode thats the reason of warnings ... 

I've almost finished my release, so I will publish it also on x86 when all tests will pass

**Comment by ichiriac** [comment]
i've made a build for you to test, i've not yet fixed libs with php_http :((

Here your link : https://github.com/expressif/win-dist/archive/php-7.0-ts-x86.zip

**Comment by laukstein** [comment]
I see no more php_libevent.dll exceptions, except it now crashes with [php_libevent.dll](https://github.com/expressif/win-dist/archive/php-7.0-ts-x86.zip) ([libraries](https://github.com/expressif/win-dist/archive/php-5.6-ts-x86.zip) works well on PHP 5.6.14)
![cli](https://cloud.githubusercontent.com/assets/183966/12008967/cf7977bc-ac6c-11e5-9df4-cfd662313102.png)
while running https://github.com/huqinlou0123/php-socket-websocket-select-epoll

```
php server/epoll-server.php
pause
```

In case you test it too, add PHP 7 compatibility https://github.com/laukstein/php-socket-websocket-select-epoll/commit/17e5ee9f7609ea7fe32fc7e01f90274b47545357.

**Comment by laukstein** [comment]
On correct start

```
 PATH=\xampp\php
 cd \www
 php epoll-server.php
 pause
```

it doesn't show any exception, except it doesn't work - client `new WebSocket("ws://127.0.0.1:8866/")` stops it immediately

```
 >pause
 Press any key to continue . . .
```

**Comment by ichiriac** [comment]
it's fixed and released : https://github.com/expressif/win-dist/archive/php-7.0-ts-x86.zip

If needed, you can now open issues directly to https://github.com/expressif/pecl-event-libevent

**Comment by laukstein** [comment]
Still crashing, like reported earlier https://github.com/expressif/win-dist/issues/1#issuecomment-167382343.
Did you really test it, with https://github.com/huqinlou0123/php-socket-websocket-select-epoll?

**Comment by ichiriac** [comment]
yes i've tested it with your code and it passes, but be aware that you need the latest php 7.0.2 release, it contains a fix on ressources allocation (download again the archive i've put the released php executables)

by the way, i hope you do not use it on production, it's an early stage release (and my migration is not yet fully stable - even if it passes 100 000 HTTP requests without memory leaks)

**Comment by laukstein** [comment]
Can you pull the proposed fix also to https://github.com/php/pecl-event-libevent?
Are you sure on closing this issue? https://github.com/expressif/win-dist/archive/php-7.0-ts-x86.zip still is missing README.md defined libraries Pecl Libevent, Pecl Propro and Pecl Raphf.
